-- MySQL Script generated by MySQL Workbench
-- 03/22/16 20:28:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema erp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema erp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `erp` DEFAULT CHARACTER SET utf8 ;
USE `erp` ;

-- -----------------------------------------------------
-- Table `erp`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`Product` ;

CREATE TABLE IF NOT EXISTS `erp`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NULL,
  `description` VARCHAR(65) NULL,
  `unitPrice` FLOAT NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`Component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`Component` ;

CREATE TABLE IF NOT EXISTS `erp`.`Component` (
  `idComponent` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NULL,
  `description` VARCHAR(65) NULL,
  PRIMARY KEY (`idComponent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`ProductComponents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`ProductComponents` ;

CREATE TABLE IF NOT EXISTS `erp`.`ProductComponents` (
  `idProduct` INT NOT NULL,
  `idComponent` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `idComponent`),
  INDEX `ComponentForProduct_idx` (`idComponent` ASC),
  CONSTRAINT `ProductFromComponents`
    FOREIGN KEY (`idProduct`)
    REFERENCES `erp`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ComponentForProduct`
    FOREIGN KEY (`idComponent`)
    REFERENCES `erp`.`Component` (`idComponent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`Country` ;

CREATE TABLE IF NOT EXISTS `erp`.`Country` (
  `idCountry` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(85) NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`Address` ;

CREATE TABLE IF NOT EXISTS `erp`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `line1` VARCHAR(45) NOT NULL,
  `line2` VARCHAR(45) NOT NULL,
  `postalCode` VARCHAR(15) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `idCountry` INT NOT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `AddressCountry_idx` (`idCountry` ASC),
  CONSTRAINT `AddressCountry`
    FOREIGN KEY (`idCountry`)
    REFERENCES `erp`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`Employee` ;

CREATE TABLE IF NOT EXISTS `erp`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `idAddress` INT NULL,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `passw` VARCHAR(45) NULL,
  `salary` FLOAT NULL,
  PRIMARY KEY (`idEmployee`),
  INDEX `EmployeeAddress_idx` (`idAddress` ASC),
  CONSTRAINT `EmployeeAddress`
    FOREIGN KEY (`idAddress`)
    REFERENCES `erp`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`Expense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`Expense` ;

CREATE TABLE IF NOT EXISTS `erp`.`Expense` (
  `idExpense` INT NOT NULL AUTO_INCREMENT,
  `idEmployee` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `date` DATETIME NOT NULL,
  `concept` VARCHAR(100) NULL,
  PRIMARY KEY (`idExpense`),
  INDEX `ExpenseByEmployee_idx` (`idEmployee` ASC),
  CONSTRAINT `ExpenseByEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `erp`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`Vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`Vendor` ;

CREATE TABLE IF NOT EXISTS `erp`.`Vendor` (
  `idVendor` INT NOT NULL AUTO_INCREMENT,
  `idAddress` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`idVendor`),
  INDEX `VendorAddress_idx` (`idAddress` ASC),
  CONSTRAINT `VendorAddress`
    FOREIGN KEY (`idAddress`)
    REFERENCES `erp`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`SaleOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`SaleOrder` ;

CREATE TABLE IF NOT EXISTS `erp`.`SaleOrder` (
  `idSaleOrder` INT NOT NULL AUTO_INCREMENT,
  `idEmployee` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `price` FLOAT NOT NULL,
  `discount` FLOAT NOT NULL,
  PRIMARY KEY (`idSaleOrder`),
  INDEX `SaleByEmployee_idx` (`idEmployee` ASC),
  CONSTRAINT `SaleByEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `erp`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`StockProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`StockProduct` ;

CREATE TABLE IF NOT EXISTS `erp`.`StockProduct` (
  `idStockProduct` INT NOT NULL AUTO_INCREMENT,
  `idProduct` INT NOT NULL,
  `idSaleOrder` INT NULL,
  `expirationDate` DATETIME NOT NULL,
  `warehouse` INT NOT NULL,
  `shelf` INT NOT NULL,
  `drawer` INT NOT NULL,
  PRIMARY KEY (`idStockProduct`),
  INDEX `StockForProduct_idx` (`idProduct` ASC),
  INDEX `SaleForStock_idx` (`idSaleOrder` ASC),
  CONSTRAINT `StockForProduct`
    FOREIGN KEY (`idProduct`)
    REFERENCES `erp`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SaleForStock`
    FOREIGN KEY (`idSaleOrder`)
    REFERENCES `erp`.`SaleOrder` (`idSaleOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`StockComponent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`StockComponent` ;

CREATE TABLE IF NOT EXISTS `erp`.`StockComponent` (
  `idStockComponent` INT NOT NULL AUTO_INCREMENT,
  `idComponent` INT NOT NULL,
  `idExpense` INT NOT NULL,
  `idVendor` INT NOT NULL,
  `idStockProduct` INT NULL,
  `warehouse` INT NOT NULL,
  `shelf` INT NOT NULL,
  `drawer` INT NOT NULL,
  `expirationDate` DATETIME NOT NULL,
  PRIMARY KEY (`idStockComponent`),
  INDEX `ComponentForStock_idx` (`idComponent` ASC),
  INDEX `StockPurchase_idx` (`idExpense` ASC),
  INDEX `StockByVendor_idx` (`idVendor` ASC),
  INDEX `StockComponentForProductStock_idx` (`idStockProduct` ASC),
  CONSTRAINT `ComponentForStock`
    FOREIGN KEY (`idComponent`)
    REFERENCES `erp`.`Component` (`idComponent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StockComponentPurchase`
    FOREIGN KEY (`idExpense`)
    REFERENCES `erp`.`Expense` (`idExpense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StockComponentByVendor`
    FOREIGN KEY (`idVendor`)
    REFERENCES `erp`.`Vendor` (`idVendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StockComponentForProductStock`
    FOREIGN KEY (`idStockProduct`)
    REFERENCES `erp`.`StockProduct` (`idStockProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`School`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`School` ;

CREATE TABLE IF NOT EXISTS `erp`.`School` (
  `idSchool` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(85) NULL,
  `idCountry` INT NULL,
  PRIMARY KEY (`idSchool`),
  INDEX `idCountry_idx` (`idCountry` ASC),
  CONSTRAINT `idCountry`
    FOREIGN KEY (`idCountry`)
    REFERENCES `erp`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`Client` ;

CREATE TABLE IF NOT EXISTS `erp`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `idAddress` INT NULL,
  `email` VARCHAR(55) NULL,
  `birthDate` DATETIME NULL,
  `idSchool` INT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `ClientAddress_idx` (`idAddress` ASC),
  INDEX `ClientSchool_idx` (`idSchool` ASC),
  CONSTRAINT `ClientAddress`
    FOREIGN KEY (`idAddress`)
    REFERENCES `erp`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClientSchool`
    FOREIGN KEY (`idSchool`)
    REFERENCES `erp`.`School` (`idSchool`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `erp`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `erp`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `erp`.`Invoice` (
  `idInvoice` INT NOT NULL AUTO_INCREMENT,
  `idSaleOrder` INT NOT NULL,
  `idClient` INT NOT NULL,
  `tax` FLOAT NOT NULL,
  `finalPrice` FLOAT NOT NULL,
  PRIMARY KEY (`idInvoice`),
  INDEX `InvoiceSaleOrder_idx` (`idSaleOrder` ASC),
  INDEX `InvoiceClient_idx` (`idClient` ASC),
  CONSTRAINT `InvoiceSaleOrder`
    FOREIGN KEY (`idSaleOrder`)
    REFERENCES `erp`.`SaleOrder` (`idSaleOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InvoiceClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `erp`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `erp`.`Country`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp`;
INSERT INTO `erp`.`Country` (`idCountry`, `name`) VALUES (1, 'Mexico');
INSERT INTO `erp`.`Country` (`idCountry`, `name`) VALUES (2, 'United States');

COMMIT;


-- -----------------------------------------------------
-- Data for table `erp`.`Address`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp`;
INSERT INTO `erp`.`Address` (`idAddress`, `line1`, `line2`, `postalCode`, `city`, `idCountry`) VALUES (1, 'Av Universidad 2014', 'B. 17 Apt. 002', '04360', 'Mexico City', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `erp`.`School`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp`;
INSERT INTO `erp`.`School` (`idSchool`, `name`, `idCountry`) VALUES (1, 'Hogwarts', 2);
INSERT INTO `erp`.`School` (`idSchool`, `name`, `idCountry`) VALUES (2, 'Durmstrang', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `erp`.`Client`
-- -----------------------------------------------------
START TRANSACTION;
USE `erp`;
INSERT INTO `erp`.`Client` (`idClient`, `name`, `lastName`, `idAddress`, `email`, `birthDate`, `idSchool`) VALUES (1, 'Juan Carlos', 'Fontecha', 1, 'jcfontecha@gmail.com', '1993-9-27', 1);

COMMIT;

