//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCRM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Address
    {
        public Address()
        {
            this.Clients = new ObservableCollection<Client>();
            this.Employees = new ObservableCollection<Employee>();
            this.Vendors = new ObservableCollection<Vendor>();
        }
    
        public int idAddress { get; set; }
        public string line1 { get; set; }
        public string line2 { get; set; }
        public string postalCode { get; set; }
        public string city { get; set; }
        public int idCountry { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ObservableCollection<Client> Clients { get; set; }
        public virtual ObservableCollection<Employee> Employees { get; set; }
        public virtual ObservableCollection<Vendor> Vendors { get; set; }
    }
}
