//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCRM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Client
    {
        public Client()
        {
            this.Invoices = new ObservableCollection<Invoice>();
        }
    
        public int idClient { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public Nullable<int> idAddress { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public Nullable<int> idSchool { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual School School { get; set; }
        public virtual ObservableCollection<Invoice> Invoices { get; set; }
    }
}
