//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCRM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Component
    {
        public Component()
        {
            this.StockComponents = new ObservableCollection<StockComponent>();
            this.Products = new ObservableCollection<Product>();
        }
    
        public int idComponent { get; set; }
        public string key { get; set; }
        public string description { get; set; }
    
        public virtual ObservableCollection<StockComponent> StockComponents { get; set; }
        public virtual ObservableCollection<Product> Products { get; set; }

        public override string ToString()
        {
            return string.Format("({0}) {1}", key, description);
        }
    }
}
