//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCRM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Expenses = new ObservableCollection<Expense>();
            this.SaleOrders = new ObservableCollection<SaleOrder>();
        }
    
        public int idEmployee { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public Nullable<int> idAddress { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string passw { get; set; }
        public Nullable<float> salary { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ObservableCollection<Expense> Expenses { get; set; }
        public virtual ObservableCollection<SaleOrder> SaleOrders { get; set; }
    }
}
