//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCRM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Expense
    {
        public Expense()
        {
            this.StockComponents = new ObservableCollection<StockComponent>();
        }
    
        public int idExpense { get; set; }
        public int idEmployee { get; set; }
        public float amount { get; set; }
        public System.DateTime date { get; set; }
        public string concept { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ObservableCollection<StockComponent> StockComponents { get; set; }
    }
}
