//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCRM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Product
    {
        public Product()
        {
            this.StockProducts = new ObservableCollection<StockProduct>();
            this.Components = new ObservableCollection<Component>();
        }
    
        public int idProduct { get; set; }
        public string key { get; set; }
        public string description { get; set; }
        public Nullable<float> unitPrice { get; set; }
    
        public virtual ObservableCollection<StockProduct> StockProducts { get; set; }
        public virtual ObservableCollection<Component> Components { get; set; }
    }
}
