//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCRM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class SaleOrder
    {
        public SaleOrder()
        {
            this.Invoices = new ObservableCollection<Invoice>();
            this.StockProducts = new ObservableCollection<StockProduct>();
        }
    
        public int idSaleOrder { get; set; }
        public int idEmployee { get; set; }
        public System.DateTime date { get; set; }
        public float price { get; set; }
        public float discount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ObservableCollection<Invoice> Invoices { get; set; }
        public virtual ObservableCollection<StockProduct> StockProducts { get; set; }
    }
}
