//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCRM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class StockProduct
    {
        public StockProduct()
        {
            this.StockComponents = new ObservableCollection<StockComponent>();
        }
    
        public int idStockProduct { get; set; }
        public int idProduct { get; set; }
        public Nullable<int> idSaleOrder { get; set; }
        public System.DateTime expirationDate { get; set; }
        public int warehouse { get; set; }
        public int shelf { get; set; }
        public int drawer { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SaleOrder SaleOrder { get; set; }
        public virtual ObservableCollection<StockComponent> StockComponents { get; set; }
    }
}
