//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCRM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.StockComponents = new ObservableCollection<StockComponent>();
        }
    
        public int idVendor { get; set; }
        public int idAddress { get; set; }
        public string name { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ObservableCollection<StockComponent> StockComponents { get; set; }
    }
}
